# Generated by Django 4.1.7 on 2023-03-17 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0004_remove_personas_correo_electronico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='persona',
            new_name='personas',
        ),
    ]
