# Generated by Django 4.1.7 on 2023-03-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0006_revisar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='av_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
