# Generated by Django 4.1.7 on 2023-03-31 01:14

import authenticacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticacion', '0002_document_types_genders_resources_resources_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=authenticacion.models.path_to_avatar),
        ),
    ]
