# Generated by Django 4.1.7 on 2023-04-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticacion', '0003_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='date_of_birth',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
    ]
