# Generated by Django 4.1.7 on 2023-04-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticacion', '0005_customuser_resettoken_customuser_roles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(upload_to=''),
        ),
    ]
